/// <reference path="../createjs-lib/index.d.ts" />
/// <reference path="../easeljs/index.d.ts" />
/// <reference path="../tweenjs/index.d.ts" />
/// <reference path="../preloadjs/index.d.ts" />
/// <reference path="../soundjs/index.d.ts" />

// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/createjs/createjs.d.ts

